/***
Last modified by: $Author: marcin.ogieglo $
on: $Date: 2018-03-21 12:09:03 +0100 (Śr, 21 mar 2018) $
in revision: $Revision: 81649 $
***/

#if !defined __ROZKAZY_H__
#define __ROZKAZY_H__ 1

#define STAN 500
#define STATE 500
#define TEMP_CO 501
#define ZADANA_CO 502
#define REGULATOR_POKOJOWY 503
#define PRACA_REGULATOR_POKOJOWY REGULATOR_POKOJOWY
#define STATUS_REGULATOR_POKOJOWY 505 //odpowiada na pytanie czy pokoj jest dogrzany
#define FUNKCJA_REGULATOR_POKOJOWY STATUS_REGULATOR_POKOJOWY
#define STATUS_PODAJNIK 506
#define FUNKCJA_PODAJNIK STATUS_PODAJNIK
#define STATUS_WIEJOK 507
#define FUNCKJA_NADMUCH STATUS_WIEJOK
#define STATUS_POMPA_CO 508
#define FUNKCJA_POMPA_CO STATUS_POMPA_CO
#define WERSJA 509
#define RECZNA 510
#define PRACA_PODAJNIK 511
#define PRACA_NADMUCH 512
#define PRACA_POMPA_CO 513
#define STATUS_POMPA_CWU 514
#define FUNKCJA_POMPA_CWU STATUS_POMPA_CWU
#define PRACA_POMPA_CWU 515
#define STALA_POMPA_CO 516
#define FUNKCJA_STALA_POMPA_CO STALA_POMPA_CO
#define TEMPCWU 517
#define STATUS_STALA_POMPA_CO 519
#define DEFAULTS 520
#define ROZPALANIE 521
#define WYGASZANIE 522
#define WYLOT 523
#define PRACA_GRZALKA 524
#define PRACA_RUSZT 525
#define TRYB_LETNI 526
#define CZUWANIE 527
#define WYLACZ 528
#define WAIT_LITTLEMORE 530
#define CURBIEG 531
#define POMPAPODLOG 532
#define POMPACYRKUL 533
#define RUN_PROGRAM 534
#define POMPAWYGASZANIE 535
#define TRANSMISSION_END 536
#define TRANSMISSION_ERROR 537
#define GO_TO_WORK 538
#define REVEAL_YOURSELF 539
#define GENERATE_ID 540
#define HERE_I_AM 541
#define RESPOND 542
//#define TYPE 543                      //zmieniono na TYP_STEROWNIKA z powodu błedów w kompliacji "core_cm3.h"
#define TYP_STEROWNIKA 543
#define STATUS_HALLOTRON 544
#define HALLOTRON_STATUS STATUS_HALLOTRON
#define FLOOR_TEMP 545
#define TEMP_PODLOGOWA FLOOR_TEMP
#define PRACA_POMPA_CYRKULACYJNA 546
#define PRACA_POMPA_PODLOGOWA 547
#define VALVE_OPEN 548
#define CANCEL_ALARM 549
#define TRANSMISSION_START 550
#define FEEDER_TIME 551
#define STATUS_GRZALKA 552
#define CODE 553
#define SERVICE_SETTINGS 554
#define AKTUALNA_IMP_CO 555
#define ZADANA_IMP_CO 556
#define AKTUALNA_IMP_SPALINY 557
#define ZADANA_IMP_SPALINY 558
#define AKTUALNA_SPALINY 559
#define TEMP_SPALINY 559
#define AKTUALNA_KLIENT_SPALINY 560
#define ZADANA_SPALINY 561
#define JEST_ZADANA_SPALINY 562
#define JEST_ZADANA_CO 563
#define POLIMPULS_CO 564
#define POLIMPULS_SPALINY 565
#define NAWIAS_SPALINY 566
#define NAWIAS_CO 567
#define MNOZNIK_CO 568
#define MNOZNIK_SPALINY 569
#define NEWBIEGWYSWIETLANIE 570
#define LICZENIEDOCHODZENIA_SPALINY 571
#define LICZENIEDOCHODZENIA_CO 572
#define WYMUS_SPALINY 573
#define WYMUS_CO 574
#define AKTUALNY_CZAS_CALKI_CO 575
#define AKTUALNY_CZAS_CALKI_SPALINY 576
#define CZAS_ROZPALANIA 577
#define HISTEREZA_CO 578
#define CZAS_PRACY 579
#define CZAS_PRACY_PODAJNIKA 579
#define CZAS_PRZERWY 580
#define CZAS_PRZERWY_PODAJNIKA 580
#define TRYB 581
#define FUNKCJA_DILE 582
#define OBROTY 583
#define OPOZNIENIE_NADMUCHU 584
#define OPOZNIENIE_PODAJNIKA 585
#define PRACA_PODTRZYMANIA 586
#define CZAS_PRACY_PODAJNIKA_PODTRZYMANIE 586
#define PRZERWA_PODTRZYMANIA 587
#define CZAS_PRZERWY_PODAJNIKA_PODTRZYMANIE 587
#define CZAS_ALARM_TEMP 588
#define FUNKCJA_PODTRZYMANIE 589
#define CWU 590
#define FUNKCJA_CWU CWU
#define HISTEREZACWU 591
#define PRZERWARUSZT_PRACA 592
#define PRZERWA_RUSZT_PRACA 592
#define PRZERWARUSZT_PODTRZYMANIE 593
#define PRZERWA_RUSZT_PODTRZYMANIE 593
#define TEMPROZPAL 594
#define TEMP_ROZPALANIA 594
#define CZASPODSYPU 595
#define CZASPRACYROZPALANIA 596
#define CZASPRZERWYROZPALANIA 597
#define CZAS_PRZERWY_ROZPALANIA 597
#define MOCNADMUCHUROZPALANIA 598
#define CZASGRZALKI 599
#define MAXROZPALANIE 600
#define MOCNADMUCHUPODTRZYMANIA 601
#define TEMPZALPOMPYCO 602
#define TEMP_ZALACZENIA_POMP TEMPZALPOMPYCO
#define MAXTEMPPODAJNIKA 603
#define CZASALARMUPODAJNIKA 604
#define MOCNADMUCHUPODTRZYMANIA_STALE 605
#define STALA_MOC_NADMUCHU_PODTRZYMANIA MOCNADMUCHUPODTRZYMANIA_STALE
#define MOCNADMUCHUPRZEJSCIE 606
#define PRACAPRZEJSCIE 607
#define PRZERWAPRZEJSCIE 608
#define TEMPPRZEJSCIE 609
#define OPOZNIENIEROZPALANIA 610
#define OPOZNIENIE_ROZPALANIA 610
#define MOCMODULACJI 611
#define PRACAMODULACJI 612
#define TEMPMODULACJI 613
#define CZASPRZEPPOMPY 614
#define CZAS_PRACY_POMPY_CO_POK 614
#define INTERWALPRZEPPOMPY 615
#define CZAS_PRZERWY_POMPY_CO_POK 615
#define PODAJNIK_NOTOFF 616
#define TEMPPRIORYTETU 617
#define ALARMOWEZALACZENIEPOMPYCO 618
#define ALARMOWE_ZALACZENIE_POMPY_CO ALARMOWEZALACZENIEPOMPYCO
#define ZADUZATEMPCO 619
#define TEMP_ALARMU_KOTLA ZADUZATEMPCO
#define DEFAULT_CZAS_PRACY 620
#define DEFAULT_CZAS_PRZERWY 621
#define CZAS_ALARMU_PODAJNIKA 622
#define MINTEMP_PODLOG 623
#define MIN_TEMP_PODLOGOWA MINTEMP_PODLOG
#define PRACA_CYRKUL 624
#define CZAS_PRACY_POMPA_CYRKULACYJNA PRACA_CYRKUL
#define PRZERWA_CYRKUL 625
#define CZAS_PRZERWY_POMPA_CYRKULACYJNA PRZERWA_CYRKUL
#define POZIOMOPTIMUM 626
#define KROKI 627
#define PRETESTOGNIACZAS 628
#define PRETESTOGNIAMOC 629
#define CZAS_PRACY_POGRZEBACZA 630
#define CZAS_PRZERWY_POGRZEBACZA 631
#define PROBKOWANIE 632
#define HISTEREZA_OGIEN 633
#define MAXCZASPRZEJSCIA 634
#define CZASPRACYPRZEJSCIA 635
#define CZASPRZERWYPRZEJSCIA 636
#define MOCNADMUCHUPRZEJSCIA 637
#define CZASWYDMUCHU 638
#define MOCNADMUCHU_WYDMUCH 639
#define MOCNADMUCHU_WYGASZANIE 640
#define FUNKCJA_POGRZEBACZ 641
#define POZIOMZGASZENIA 642
#define JASNOSC 643
#define CZASOPTIMUM 644
#define ROZDZIELCZOSC 645
#define ALARMRUSZTA 646
#define MAXTEMP_PODLOG 647
#define MAX_TEMP_PODLOGOWA MAXTEMP_PODLOG
#define STANDBY 648
#define ADDRESS 649
#define CZAS_PODTRZYMANIA_T2 650
#define FINAL_CRATES 651
#define VALVE_TEMP 652
#define VALVE_TIME 653
#define TEMPZADCWU 654
#define VALVE_MINOPEN 655
#define VALVE_UNITJUMP 656
#define VALVE_INTERVAL 657
#define WEEK_START_HOUR 658
#define WEEK_START_MINUTE 659
#define WEEK_END_HOUR 660
#define WEEK_END_MINUTE 661
#define WEEK_TEMPERATURE 662
#define WEEK_MODE 663
#define TIME 664
#define DAY 665
#define STATUS_POMPA_PODLOGOWA 666
#define FUNKCJA_POMPA_PODLOGOWA STATUS_POMPA_PODLOGOWA
#define STATUS_POMPA_CYRKULACYJNA 667
#define FUNKCJA_POMPA_CYRKULACYJNA STATUS_POMPA_CYRKULACYJNA
#define VALVE_TYPE 668
#define PALIWO 669
#define PRACA_WIEJOK_PODTRZYMANIE 670
#define PRZERWA_WIEJOK_PODTRZYMANIE 671
#define START_MODE 672
#define ANTYSTOP_POMP 673
#define CWU_LATO 674
#define FUNKCJA_LATO CWU_LATO
#define CIRCULATION_ZONE_DATA 675
#define OPOZNIENIE_WENTYLATORA_PO_GRZALCE 676
#define CZAS_POZIOMU_ROZPALANIA 677
#define POMPA_CO_POKOJOWKA 678
#define STATUS_ZAWORU 679
#define MAX_TEMP_SPALINY 680
#define MIN_TEMP_SPALINY 681
#define ZMIANA_SPALINY 682
#define ZAKRES_SPALINY 683
#define CZAS_CALKI_SPALINY 684
#define CZAS_CALKI_ZADANA_SPALINY 685
#define PRZEKLADNIA_SPALINY 686
#define PRZEKLADNIA_MOC_SPALINY 687
#define PROG_TEMP_SPALINY 688
#define CZAS_TESTU_SPALINY 689
#define CZAS_CALKI_IMP_NIZEJ_SPALINY 690
#define CZAS_CALKI_IMP_WYZEJ_SPALINY 691
#define PROG_TESTU_SPALINY 692
#define OPOZNIENIE_TESTU_SPALINY 693
#define ZMIANA_BIEGU_SPALINY 694
#define CZAS_CALKI_NAWIAS_SPALINY 695
#define DZIELNIK_SPALINY 696
#define OPOZ_PRZYTRZ_SPALINY 697
#define KASOW_OPOZ_PRZYTRZ_SPALINY 698
#define CALKA_SPALINY 699
#define PRZEPISYWANIE_SPALINY 700
#define BLOK_CALKI_CO_SPALINY 701
#define ODBLOK_CALKI_CO_SPALINY 702
#define MAX_CZAS_DOCH_SPALINY 703
#define ZMIANA_CALKI_SPALINY 704
#define START_LICZENIA_SPALINY 705
#define ZAKRES_CO 706
#define CZAS_CALKI_CO 707
#define CZAS_CALKI_ZADANA_CO 708
#define CZAS_CALKI_ALARM_CO 709
#define CZAS_CALKI_ALARM_ZADANA_CO 710
#define PRZEKLADNIA_CO 711
#define PRZEKLADNIA_MOC_CO 712
#define CALKA_CO 713
#define PUNKT_ZMIANY_CO 714
#define CZAS_CALKI_IMP_NIZEJ_CO 715
#define CZAS_CALKI_IMP_WYZEJ_CO 716
#define ZMIANA_IMPULS_CO 717
#define MIN_PRACA_CO 718
#define MAX_PRACA_CO 719
#define MIN_PRZERWA_CO 720
#define MAX_PRZERWA_CO 721
#define MIN_PRACA_ROZPAL_CO 722
#define MAX_PRACA_ROZPAL_CO 723
#define MIN_PRZERWA_ROZPAL_CO 724
#define MAX_PRZERWA_ROZPAL_CO 725
#define CZAS_CALKI_NAWIAS_CO 726
#define DZIELNIK_CO 727
#define MAX_CZAS_DOCH_CO 728
#define ZMIANA_CALKI_CO 729
#define START_LICZENIA_CO 730
#define CZAS_ALARMU_ROZPALANIA 731
#define MAX_WENTYLATOR 732
#define MIN_WENTYLATOR 733
#define CZAS_WYGASZANIA 734
#define MAX_ZADANA_CWU 735
#define MOC_PODTRZYMANIA 736
#define TYP_WENTYLATORA 737
#define MOC_NADMUCHU_ROZPALANIA MOCNADMUCHUROZPALANIA
#define MOC_NADMUCHU_PRACY 738
#define MOC_NADMUCHU_PODTRZYMANIA MOCNADMUCHUPODTRZYMANIA
#define MAX_ROZPALANIE MAXROZPALANIE
#define BIEG_ROZDMUCHU 739
#define MOC_NADMUCHU_ROZPALANIA_2 740
#define MOC_NADMUCHU_ROZPALANIA2 740
#define MOC_NADMUCHU_ROZPALANIA_3 741
#define MOC_NADMUCHU_ROZPALANIA3 741
#define TEMP_CWU 742
#define ZADANA_CWU TEMPZADCWU
#define HISTEREZA_CWU HISTEREZACWU
#define MAX_TEMP_ROZPALANIE_SPALINY 745
#define WZROST_TEMP_ROZPALANIA2 746
#define WZROST_TEMP_ROZPALANIA 747
#define CZAS_TESTU_OGNIA 748
#define CZAS_MNOZNIKA_PALIWA 749
#define MNOZNIK_PALIWA 750
#define ROZNICA_MNOZNIKA_PALIWA 751
#define PRACA_SLIMAK_PALNIKA 752
#define PRACA_POGRZEBACZ 753
#define FUNKCJA_KLAPA 754
#define STAN_KLAPA 755
#define STAN_KRANCOWKA_PALNIKA 756
#define POMPA_CWU_LATO 757
#define PRACA_PRZEPALANIE_POMPY 758
#define VALVE_ZADANA_TEMP 759
#define FUNKCJA_VALVE 760
#define FUNKCJA_ZAWOR FUNKCJA_VALVE
#define TEMP_ZEWNETRZNA 761
#define PROG_TEMPERATURY_PRZEJSCIA 762
#define CZAS_PROGU_PRZEJSCIA 763
#define ZEGAR TIME // starszy bajt danych - godzina, mlodszy - minuta
#define DZIEN_TYGODNIA DAY // 0 = niedziela
#define TYGODNIOWKA_ZMIANA_ZADANEJ_CO 764
#define ROZNICA_MNOZNIKA_DAWKI 765
#define MNOZNIK_DAWKI 766
#define CZAS_MNOZNIK_DAWKI 767
#define WEEK_IN_ZONE 768
#define RC 769
#define TRYB_PALENIA 770
#define FUNKCJA_ANTIFREEZE_POMP 771
#define ANTIFREEZE_POMP_TEMPERATURA 772
#define FUNKCJA_ANTYSTOP_POMP 773
#define ANTYSTOP_POMP_DZIEN_ZALACZENIA 774
#define ANTYSTOP_POMP_CZAS_DZIALANIA 775
#define ANTYSTOP_POMP_GODZINA_ZALACZENIA 776
#define ZAWOR_ZAMKNIECIE_OD_POKOJOWKI 777
#define FUNKCJA_LEGIONELLA 778
#define PRACA_LEGIONELLA 779
#define GODZINA_ROZPOCZECIA_LEGIONELLA 780
#define CZAS_TRWANIA_LEGIONELLA 781
#define DZIEN_ROZPOCZECIA_LEGIONELLA 782
#define ZADANA_CWU_LEGIONELLA 783
#define MAX_CZAS_TRWANIA_LEGIONELLA 784
#define TEMP_POKOJOWA 785
#define ZADANA_TEMP_POKOJOWA 786
#define WEEK_ZONE_DATA 787
#define WEEK_ZONE_DAY 788
#define DOGRZANY_BOJLER 789
#define MINMAX_CO 790 // starszy bajt danych max, mlodszy min
#define MINMAX_CWU 791 // starszy bajt danych max, mlodszy min
#define CZAS_PRACY_TEST_OGNIA 792
#define CZAS_PRZERWY_TEST_OGNIA 793
#define TRYB_PRACY_ZAWORU 794 //okreďż˝la tryb pracy zaworu (praca normalna, zwykďż˝a pokojďż˝wka, nowa pokojďż˝wka itp.)
#define ZAWOR_PROPORTIONAL_GAIN 795
#define IMPULSY_NA_PROCENT 796
#define OPOZNIENIE_WYLACZENIA_WENTYLATORA_PODTRZYMANIE 797
#define ZALACZ_ZAWOR 798
#define PROG_WYLACZENIA_PODAWANIA 799
#define TYP_POMPY 800
#define FUNKCJA_CZUJNIK_OGNIA 801
#define JEST_PALIWO 802
#define CZAS_BRAKU_PALIWA 803
#define CZAS_MARTWEGO_PUNKTU_PODAJNIKA 804
#define TEMPERATURA_POMPY_DODATKOWEJ 805
#define PRACA_POMPY_DODATKOWEJ 806
#define FUNKCJA_POMPY_DODATKOWEJ 807
#define TYP_POMPY_DODATKOWEJ 808
#define CZAS_PRACY_POMPY_DODATKOWEJ 809
#define CZAS_PRZERWY_POMPY_DODATKOWEJ 810
#define MIN_TEMPERATURA_POMPY_DODATKOWEJ 811
#define MAX_TEMPERATURA_POMPY_DODATKOWEJ 812
#define DOBOWKA_POMPY_DODATKOWEJ 813
#define NUMER_POMPY_DODATKOWEJ 814
#define ZAWOR_TEMPERATURA_ZADANA_POKOJOWKI 815//okresla temperature zadana jaka ma byc utrzymywana przez zawor przy dogrzanej pokojowce
#define FUNKCJA_POMPY_ZAWORU 816
#define PRACA_POMPY_ZAWORU 817
#define TYGODNIOWKA_ZMIANA_ZADANEJ_ZAWORU 818
#define TYP_KRANCOWKI_PALNIKA 819
#define MINIMALNA_TEMPERATURA_POWROTU 820
#define ZAWOR_PRZYMKNIECIE_POWROT 821
#define ZABEZPIECZENIE_HALLOTRONU_RUSZT 822
#define STAN_STEROWNIKA_RUSZT 823
#define FUNKCJA_OCHRONY_POWROTU 824
#define TEMPERATURA_POWROTU 825
#define VALVE_ADRESS 826
#define VALVE_MINMAX_ZADANA 827 // starszy b. max, mlodszy b. min
#define CZAS_BEZ_WYGASZANIA 828
#define TRYB_PRACY_KOTLA 829
#define TEMPERATURA_POMIESZCZENIA 830 // ustawianie temperatury pomieszczenia w zaworze przy sterowaniu dynamicznym z pokojówki
#define TEMPERATURA_ZADANA_POMIESZCZENIA 831 // ustawianie temperatury zadanej pomieszczenia w zaworze przy sterowaniu dynamicznym z pokojówki
#define JEZYK 832
#define ROZNICA_TEMPERATURY_POMIESZCZENIA 833
#define ZMIANA_ZADANEJ_ZAWORU 834
#define RODZAJ_TRYBU_LETNIEGO 835
#define PROG_POMPY_CYRKULACYJNEJ 836
#define ZWIEKSZENIE_ZADANEJ_CWU 837
#define ZAWOR_KALIBRACJA 838
#define POGODOWKA_ZADANA_DLA_PROGU 839//starszy bajt okresla prog temperatury zewnetrznej (np. -20, 0, 20), mlodszy bajt - zadana dla tego progu (ilosc progow i ich wartosci sa umowne)
#define MAKSYMALNA_TEMPERATURA_POWROTU 840
#define CZAS_USREDNIANIA_TEMP_ZEWNETRZNEJ 841
#define FUNKCJA_TEMP_ZEWNETRZNA 842 //okresla czy master ma czujnik/dane temp zewnetrznej
#define FUNKCJA_ZPID 843
#define TEMP_MOSFET 844
#define CZAS_PRACY_WENTYLTORA_PODTRZYMANIE 845
#define CZAS_PRZERWY_WENTYLTORA_PODTRZYMANIE 846
#define DRUGI_CZUJNIK_BUFORA 847
#define FUNKCJA_POMPA_CO_LATO 848
#define SONDA_TYP 849  		// wybďż˝r miďż˝dzy serwomechanizmem a siďż˝ownikiem
#define SONDA_REVERT 850	// kierunek obrotu
#define SONDA_ZAKRES 851	// max kďż˝t otwarcia / max napiďż˝cie
#define SONDA_MIN	852		// trim serwo / min mapiďż˝cie
#define SONDA_DELAY 853		// opďż˝znienie wzgledem pomiaru.
#define MAX_DOLNEGO_CZUJNIKA_BUFORA 854
#define MAX_GORNEGO_CZUJNIKA_BUFORA 855
#define TEMP_GORNEGO_CZUJNIKA_BUFORA 856
#define FUNKCJA_STEROWANIE_POGODOWE 857
#define SONDA_SPEED 858
#define WZROST_TEMPERATURY_SPALIN_WYL_GRZALKI 859 // zadanie #919
#define CZAS_POWTORNEGO_ZALACZENIA_GRZALKI 860    // zadanie #919
#define WARTOSC_PROGU_POGODOWKI 861
#define OBNIZENIE_POKOJOWKI 862 //ilosc stopni o jaka ma sie obnizyc zadana po dogrzaniu pokojowki
#define GSM_ON 863
#define GSM_CPIN 864
#define GSM_NUMER_TELEFONU 865 //index, wartosc
#define GSM_PIN_AUTORYZACJA 866
#define GSM_ZASIEG 867
#define TEMP_BUFORA 868
#define GSM_BLAD 869
#define ZAWOR_TEMPERATURY_Z_MASTERA 870//okresla, czy zawor ma korzystac z temperatur ze swoich czujnikow, czy z temperatur przesylanych przez sterownik mastera
#define VALVE_INDX 871//okresla nr zaworu w sterowniku glownym (poczynajac od 1)
#define POTWIERDZENIE 872
#define KG_PALIWA 873 //ilosc paliwa w kg (starsze 7bitow procent, pozostale ilosc kg)
#define GODZINY_PALIWA 874 //przewidywany czas (godz) zuzycia paliwa
#define VALVE_DEFAULTS 875 //ustawienia fabryczne dotyczace zaworow
#define BLAD_CZUJNIKA_POKOJOWKI 876 //tutaj, a nie w states.h by nie powodowac zatrzymania pracy pozostalych sterownikow
#define FUNKCJA_OBLICZ_ZUZYCIE 877 //*true* zaĹ‚Ä…cza obliczanie podawania paliwa
#define WAGA_PALIWA 878 // waga przesypanego (podczas obliczania) paliwa
#define CZAS_OBLICZANIA_ZUZYCIA 879 // czas, przez jaki podajnik pracuje podczas obliczania
#define TEMPERATURA_PODAJNIKA 880
#define NUMER_URZADZENIA 881 //wykorzystujemy zamiast VALVE_INDX i NUMER_POMPY_DODATKOWEJ - w sterowniku domyslnie jest ustawione na 0
#define ETHERNET_ADRES_IP 882 //w starszym bajcie przekazujemy numer bajtu adresu ip a w mlodszym bajt adresu ip
#define ETHERNET_MASKA 883
#define ETHERNET_ADRES_BRAMY 884
#define ETHERNET_ADRES_DNS 885
#define ETHERNET_DHCP 886
#define FIRMA 887
#define ETHERNET_RESET_HASLA 888//rozkaz sĹ‚uĹĽÄ…cy do resetowania zapomnianego hasĹ‚a w module internetowym
#define SOLAR_TEMP_C1 889 //x10
#define SOLAR_TEMP_C2 890 //x10
#define SOLAR_TEMP_C3 891 //x10
#define SOLAR_TEMP_C4 892 //x10
#define SOLAR_TRYB_PRACY 893 // 0 AUTO, 1 ODMRAZANIE KOLEKTORA, 2 WAKACYJNY
#define GSM_COPS 894				//nazwa operatora  //index, wartosc
#define GSM_CSPN 895				//indentyfikator sieci //index, wartosc
#define RESET_PALIWA 896 // reset licznikĂłw zuĹĽycia paliwa
#define WAGA_PALIWA_ZASOBNIK 897 // waga paliwa w zasobniku
#define ZAWOR_OBLICZONA_ZMIANA_ZADANEJ 898//zmiana zadanej po uwzglednieniu dogrzania regulatora pokojowego lub innych zmian na podstawie np. tygodniowki
#define ETHERNET_STATUS 899
#define NADMUCH_PALENIE_RECZNE 900 // zalaczenie/wylaczenie wentylatora w paleniu recznym
#define NADMUCH_P_RECZNE_PRACA 901 // czas pracy nadmuchu w podtrzymaniu gdy palenie reczne
#define NADMUCH_P_RECZNE_PRZERWA 902 // czas przerwy nadmuchu w podtrzymaniu gdy palenie reczne
#define ETHERNET_STATUS_MODULU 903 // status moduĹ‚u internetowego
#define ETHERNET_ADRES_MAC 904
#define SONDA_PRACA 905 //włączanie i wyłącznie sterownika sondy lambda
#define STAN_PRZEPUSTNICA 906
#define PRZEPUSTNICA_PRAWO 907
#define PRZEPUSTNICA_LEWO 908
#define PRACA_PIEC_ZEWNETRZNY  909
#define TEMP_ZALACZENIA_PIECA 910
#define RECZNA_WYJDZ 911
#define ALARM 912
#define STAN_BUFOR_CIEPLA 913 //get/set aktualny stan bufora ciepla (zał/wył)
#define STAN_PRZEPUSTNICA_ZAJETA 914
#define PRZEPUSTNICA_KALIBRACJA 915
#define PRZEPUSTNICA_CZAS_KKALIBRACJI 916 //czas korekty kalibracji w sek.
#define PRZEPUSTNICA_CZAS_DO_KKALIBRACJI 917 //pozostaly czas korekty kalibracji w sek.
#define STAN_PIEC_ZEWNETRZNY 918 //zalaczanie/wylaczanie obslugi pieca lub innego zr ciepa
#define PRZEPUSTNICA_KALIBRACJA_IMPULSY 919 //na ile impów skaliborowana przepustnica
#define PRZEPUSTNICA_OTWARCIE_IMPULSY 920 // na ile impów otwarta przeputnica
#define AKTUALNA_CO 921
#define ZADANA_CO_PID 922
#define AKTUALNA_SPALINY_PID 923
#define PIERW_BLOK_CALKI_CO_SPALINY 924
#define PIERW_ODBLOK_CALKI_CO_SPALINY 925
#define MIN_ZADANA_CO 926
#define WEEK_2_ZONE_DATA 927
#define WEEK_2_ZONE_DAY 928
#define WEEK_2_MODE 929
#define WEEK_2_ERASE 930
#define WSPOLCZYNNIK_WENTYLATORA 931
#define WSPOLCZYNNIK_PODAWANIA 932
#define ZAKRES_WSPOLCZYNNIKA_WENTYLATORA 933
#define NUMER_EDYTOWANEGO_PALIWA 934
#define TEMP_WYGASZNIA 935
#define TEMP_ZALACZENIA_POMPY_CWU 936
#define HISTEREZA_PODLOGOWEJ 937
#define PRZEPUSTNICA_ZALACZONA 938
#define HISTEREZA_BUFORA 939
#define KALIBRACJA_CZUJNIKA_ZEWNETRZNEGO 940//ilosc stopni o jaka ma sie zmienic odczytana temperatura zewnetrzna (mnozone razy 10)
#define WERSJA_PID 941
#define WERSJA_PARAMETROW_PID 942
#define PRACA_STYKU_BEZNAPIECIOWEGO 943
#define CZYSZCZENIE_RUSZTA_PRZERWA 944
#define RUSZT_OCZYSC_TERAZ 945
#define OCHRONA_KOTLA 946//przesyla informacje czy w danej chwili dziala ochrona powrotu lub kotla
#define TYP_KOTLA 947//INFORMACJE O RODZAJU KOTLA
#define PRACA_STYK_PALNIKA 948//informacja o załączonym styku palnika - pierwotnie wykorzystany w ST-491
#define CZAS_ROZGRZANIA_PALNIKA 949
#define PRACA_NAWIEWU_RECZNA 950
#define SILA_NAWIEWU_RECZNA 951
#define PRACA_NAWIEWU 952
#define SILA_NAWIEWU 953
#define TEMP_KOLEKTORA 954
#define TEMP_ZBIORNIKA 955
#define PRACA_POMPMY_KOLEKTORA 956
#define EDYCJA_WENTYLATORA_MIN 957
#define EDYCJA_WENTYLATORA_MAX 958
#define BIERZACE_OBROTY 959
#define BIEZACE_OBROTY 959
#define DOCELOWE_OBROTY 960
#define ZAPISZ_ZMIANE 961
#define STATUS_CZUJNIK_SPALINY 962
#define EDYCJA_WENTYLATORA_MIN_OBROTY 963
#define EDYCJA_WENTYLATORA_MAX_OBROTY 964
#define MAX_WENTYLATOR_OBROTY 965
#define MIN_WENTYLATOR_OBROTY 966
#define MIN_OBROTY_PRODUCENT 967
#define MAX_OBROTY_PRODUCENT 968
#define MAKSIMUM_OBROTY_WENTYLATORA 969
#define MINIMUM_OBROTY_WENTYLATORA 970
#define PROG_POMPY_ZAWORU 971
#define SONDA_VOLTS 972
#define SONDA_IMPULSES 973
#define SOLAR_SCHEMAT 974
#define SOLAR_BIEG_URZADZENIA_1 975
#define SOLAR_BIEG_URZADZENIA_2 976
#define SOLAR_BIEG_URZADZENIA_3 977
#define SOLAR_URZADZENIE_DODATKOWE 978
#define BOILER_DOGRZANY 979
#define WEEK_ERASE 980
#define PODAJNIK_AUTO 981
#define CZAS_PRACY_CWU_LATO 982
#define CZAS_PRZERWY_CWU_LATO 983
#define HALOTRON_NADMUCH 984
#define IMPULSY_WZROSTU 985
#define CZAS_REAKCJI_ZGRUBNY 986
#define CZAS_REAKCJI_PRECYZYJNY 987
#define WSP_PROPORCJONALNY 988
#define SONDA_SKOK_NAPIECIA 989
#define SONDA_SKOK_SILOWNIKA 990
#define SONDA_ZADANA_LAMBDA 991
#define SONDA_STATUS_SONDY 992
#define SONDA_LAMBDA 993
#define SONDA_SILOWNIK_OTWARCIE 994
#define PRACA_PRZEPALANIA 995
#define PRZERWA_PRZEPALANIA 996
#define PRACA_WENTYLATOR_NADZOR 997
#define PRZERWA_WENTYLATOR_NADZOR 998
#define MOC_WENTYLATOR_NADZOR 999
#define SONDA_CZAS_DO_AKUTALIZACJI 1000
#define PRACA_POMPA_BUFORA 1001
#define TYP_POKOJOWKI 1002
#define STAN_DRZWI_PALENISKA 1003
#define STATUS_FUNKCJI 1004
#define SONDA_PRODUCENTA_MIN_SILOWNIK_PIERWOTNY 1005
#define SONDA_PRODUCENTA_MAX_SILOWNIK_PIERWOTNY 1006
#define SONDA_PRODUCENTA_MIN_SILOWNIK_WTORNY 1007
#define SONDA_PRODUCENTA_MAX_SILOWNIK_WTORNY 1008
#define SONDA_ROBOCZE_MIN_SILOWNIK_PIERWOTNY 1009
#define SONDA_ROBOCZE_MAX_SILOWNIK_PIERWOTNY 1010
#define SONDA_ROBOCZE_MIN_SILOWNIK_WTORNY 1011
#define SONDA_ROBOCZE_MAX_SILOWNIK_WTORNY 1012
#define SONDA_TRYB_USTAWIANIA_SILOWNIKOW 1013
#define KOREKTA_ZADANEJ_ZAWORU 1014 //służy do ustawiania zmiany zadanej zaworu ze sterownika głównego np. na podstawie jego pokojówki. Zmiana ta będzie utrzymywana przez czas 1 minuty od momentu jej przekazania (musi być odświeżana w komunikacji)
#define PRZEPUSTNICA_TEST_IMPULSOW 1015
#define PRZEPUSTNICA_TEST_IMPULSOW_LICZNIK 1016
#define PRZEPUSTNICA_TEST_IMPULSOW_FAZA 1017
#define PRZEPUSTNICA_TEST_IMPULSOW_DANE 1018 //zakodowane dane testu impulsów 0xff - max impulsy, 0xff00 - tolerancja testu
#define RECZNA_FLAGI 1019 //zakodowane stany dla pracy recznej urzadzen 2 stanowych.
#define PRZEPUSTNICA_RECZNA_OTWARCIE 1020
#define SONDA_SILOWNIK_INDEX 1021
#define BRAK_KOMUNIKACJI_Z_MODULEM 1022 //informuje inne moduły o braku komunikacji z poszczegolnymi modułami starszy bajt przeznaczony jest na prywatne informacje dodatkowe, w mlodszym bajcie znajduje sie klasa sterownika z pliku common.h
#define CZAS_PRACY_RUSZTU_W_WYGASZANIU 1023
#define RAW_DATA 1024 // rozkaz pozwalający na przesyłanie danych surowych po jego wystąpieniu. Pierwszym bajtem danej tego rozkazu jest numer pakietu startowego, drugim - ilość pakietów przesyłanych jako dane surowe
#define MODUL_INT_DOCELOWY_KLIENT 1025 // pozwala na wybór klienta do którego maja być wysłane kolejne pakiety. Jako że można wysyłać dane do różnych klientów należy podawać to jako flagi bitowe. Flagi są zdefiniowane w common.h
#define DANE_DO_POBRANIA 1026 // pozwala na to, żeby dowiedzieć się jaki rozkaz jest do pobrania ze slave'a 
#define MODUL_INT_PARAMETR_ROZKAZU 1027 // pozwala na zdefiniowanie dodatkowego identyfikatora dla rozkazu, w celu zapewnienia jego unikalności. Wykorzystywany np. przy przesyłanie tygodniówki lub statystyk itp.
#define MINMAX_ZADANA_POKOJOWA 1028 // pokojówka ma za zadanie odpowiedzieć na ten rozkaz w celu przekazania minimalnej i maksymalnej nastawy. Starszy bajt danych zawiera max, mlodszy - min
#define ZADANA_TEMP_POKOJOWA_UZYTKOWNIKA 1029 // surowa zadana pokojówki bez uwzględniania korekt wynikających np. z tygodniówki
#define ZADANA_TEMP_POKOJOWA_KOREKTA 1030 // korekta zadanej pokojówki wynikająca np. z tygodniówki
#define DZIEN_OD 1031  // godzina, o ktorej zaczyna sie dzien, wyrazona w minutach od polnocy
#define NOC_OD 1032    // godzina, o ktorej zaczyna sie noc, wyrazona w minutach od polnocy
//#define DEMO 1033    // wł/wył demo przpustnic w kominku
#define PRZEPUSTNICA_DANE_DIAGNOSTYCZNE 1034    // dane diagnostyczne działania przepustnicy
#define PRZEDMUCH_KOMINEK_CZAS_OTWARCIA 1035
#define PRZEDMUCH_KOMINEK_CZAS_PRZERWA 1036
#define PRZEDMUCH_KOMINEK_CZAS_TRWANIA 1037
#define TEMP_NAWIEWANA 1038
#define TEMP_WYRZUTOWA 1039
#define REKUPERATOR_PROGRAM_DZIEN 1040 //START - rozkazy konfiguracji programów tygodniowych rekuperatora
#define STREFA_DNIA_INDEX 1041
#define STREFA_DNIA_START_STOP 1042
#define STREFA_DNIA_BIEG_I_ZADANA 1043 //END
#define BIEG_WENTYLATORA_WYWIEW_RECZNA 1045
#define BIEG_WENTYLATORA_NAWIEW_RECZNA 1046
#define BIEG_WENTYLATORA_WYWIEW 1047
#define BIEG_WENTYLATORA_NAWIEW 1048
#define BYPASS_CZAS_POZOSTALY 1049
#define BYPASS_STAN 1050
#define URLOP_CZAS_POZOSTALY 1051
#define TRYB_KOMINKA_CZAS_POZOSTALY 1052
#define TRYB_KOMINKA_AKTYWNY 1053
#define PARTY_CZAS_POZOSTALY 1054
#define GRZANIE_CZAS_POZOSTALY 1055
#define CHLODZENIE_CZAS_POZOSTALY 1056
#define FUNKCJA_GRZANIA 1057
#define FUNKCJA_CHLODZENIA 1058
#define KALIBRACJA_CZUJNIKA_WYRZTU 1059
#define KALIBRACJA_CZUJNIKA_POKOJOWEGO 1060
#define KALIBRACJA_CZUJNIKA_NAWIEWU 1061
#define KOREKTA_BIEGU_WYWIEWU 1062
#define KOREKTA_BIEGU_NAWIEWU 1063
#define MOC_BIEGU_I 1064
#define MOC_BIEGU_II 1065
#define MOC_BIEGU_III 1066
#define TEMPERATURA_KOMORY_CHLOD 1067
#define TEMPERATURA_PAROWNIKA 1068
#define CHLOD_DEFROST 1069
#define CHLOD_SWIATLO 1070
#define CHLOD_ENS 1071
#define ZADANA_KOMORA_CHLOD 1072
#define DATA 1073  //zawiera date kalendarzową zakodowaną |5b-dzien|4b miesiac|7b ostatnie 2 cyfry roku|
#define STANY_URZADZEN 1074
#define STAN_ZESPOL_CHLODNICZY 1075 //stan modułu obsługującego zespół chłodniczy
#define STEROWNIE_OSWIETLENIEM_TYP 1076 //rodzaj sterownia oświetleniem
#define STEROWNIE_OSZCZEDZANIEM_ENERGII_TYP 1077 //rodzaj sterownia oszczedzaniem energii
#define OSWIETLENIE_ZAKRES_PON_PT 1079
#define OSWIETLENIE_ZAKRES_SOBOTA 1080
#define OSWIETLENIE_ZAKRES_NIEDZIELA 1081
#define OSZCZEDZANIE_ENERGII_ZAKRES_PON_PT 1082
#define OSZCZEDZANIE_ENERGII_ZAKRES_SOBOTA 1083
#define OSZCZEDZANIE_ENERGII_ZAKRES_NIEDZIELA 1084
#define ZADANA_KOMORA_CHLOD_MAX_MIN 1085
#define ZADANA_KOMORA_CHLOD_SKOK 1086
#define RUSZT_CZAS_WYSUWANIA 1087 //czas wysuwania rusztu w sekundach
#define RUSZT_CZAS_POWROTU 1088 //czas powrotu rusztu w sekundach
#define STAN_ELEKTROZAWORU 1089 //stany elektrozaworu w common.h
#define TYP_CENTRALI_REKUPERATORA 1090
#define OBROTY_NAWIEW 1091 //wentylatory rekuperatora [RPM]
#define OBROTY_WYWIEW 1092 //wentylatory rekuperatora [RPM]
#define BLOKADA_TRYBU_PRACY 1093 //wyslanie wartosci true powoduje przełączenie i blokade trybu pracy i zadanej w pokojówce do listwy elektrozawrów
#define FAZA_DEFROSTU 1094
#define HISTEREZA_KOMORY_CHLOD 1095
#define ZLICZONA_ENERGIA_ROK 1096
#define ZLICZONA_ENERGIA_MIESIAC 1097
#define ZLICZONA_ENERGIA_UBIEGLY_ROK 1098
#define ZLICZONA_ENERGIA_UBIEGLY_MIESIAC 1099
#define PRACA_ANTYZAMARZANIE_WYMIENNIKA 1100 //sygnalizuje czy pracuja algorytmy antyzamarzania wymiennika rekuperatora
#define ALGORYTM_ANTYZAMARZANIE_WYMIENNIKA 1101 //sygnalizuje jaki algorytm odpowiada sie zantyzamarzanie
#define BLOKADA_STEROWNIKA 1102 // true/false   wskazuje czy praca sterownika jest zablokowana
#define PIN_ODBLOKOWANIA_STEROWNIKA 1103 // przesyłanie kodu odblokowania sterownika, kodowanie BCD, MSB jest indeksem czesci pinu
#define INFO_CZYSZCZENIE_WENTYLATOROW 1104 // przesylanie informacji i koniecznosci czyszczenia wentylatorow i zwrotnej rekacji uzytkownika (akceptacja/odlozenie komunikatu)
#define ROBOCZE_MINMAX_WENTYLATORA_NAWIEWU 1105 //rekuperator
#define ROBOCZE_MINMAX_WENTYLATORA_WYWIEWU 1106 //rekuperator
#define ROZPALANIE_AUTOMATYCZNE 1107 //czy ma nastepowac rozpalanie automatyczne w kotle pelletowym
#define SYNCHRONIZUJ_RUSZT 1108 //data==1 rozpoczyna synchronizację rusztu
#define PIN_ZIARNO 1109
#define PIN_KOD 1110
#define TEMP_DOLNEGO_CZUJNIKA_BUFORA 1111
#define STAN_TRANSOPTORA 1112
#define TEMP_ZALACZENIA_ZAWORU 1113 //zawór 2 stanowy
#define TEMP_DELTA_POMPA 1114
#define TEMP_DELTA_ZAWOR 1115
#define TEMP_DELTA_STYK 1116
#define HISTEREZA_ZAWORU 1117 //zawor 2 stanowy
#define KRZYWA_GRZEWCZA_WYBOR 1118
#define TYP_ELEKTROZAWORU 1119 //typy elektrozaworu w common.h
#define MOC_UKLADU 1120
#define JEST_TRYB_PODRZEDNY 1121
#define OTWARCIE_PRZEPUSTNICY_PRACA 1122
#define PRZEPUSTNICA_PRACA_MODYFIKATOR 1123
#define PROG_ROZPALANIA_SPALINY 1124
#define PRACA_NAWIEW 1125
#define NAWIEW_BIEG 1126
#define ODLICZ_WYGASZANIE 1127          // czas po którym startuje wygaszanie jesli temp. spadnie poniżej okreslonej temp. spalin (zależne od TEMP_STARTU_WYGASZANIA)
#define TEMP_STARTU_WYGASZANIA 1128     //temperatura po której startuje wygaszanie jesli nie wzrosnie po okreslonym czasie (zależne od ODLICZ_WYGASZANIE)
#define PROG_WYGASZANIA_SPALINY 1129
#define PIERWSZE_URUCHOMIENIE 1130
#define RAW_DATA_ESCAPE_SEQUENCE 1131   //pseudorozkaz do escape'owania TRANSMISSION_START i TRANSMISSION_END
#define MOC_WENTYLATOR_ROZPALANIE 1132
#define MOC_WENTYLATOR_PRACA 1133
#define MOC_WENTYLATOR_WYGASZANIE 1134
#define PRACA_KOMINKA 1135
#define CYKL_PODAJNIKA 1136
#define CZAS_PODAJNIKA_ROZPALANIE 1137
#define CZAS_PODAJNIKA_PRACA 1138
#define CZAS_ZABEZPIECZENIA_GRZALKI 1139
#define DELTA_SPALIN 1140 //wzrost spalin wymagany do rozpalenia
#define TYGODNIOWKA_FLAGI_LSB 1141
#define TYGODNIOWKA_FLAGI_MSB 1142
#define TYGODNIOWKA_ZAPISZ 1143
#define KOMINEK_SCHEMAT 1144
#define TRYB_PRACY_INTEGRATORA 1145
#define REGULACJA_ILOSCI_POWIETRZA 1146
#define BIEG_EDYCJI_WENTYLATORA 1147
#define TEMP_ZRZUTU_CIEPLA_CWU 1148
#define TYGODNIOWKA_ZADANA_EKONOMICZNA 1149  //do tygodniówek opartych na dwóch temperaturach zadanych
#define TYGODNIOWKA_ZADANA_KOMFORTOWA 1150   //do tygodniówek opartych na dwóch temperaturach zadanych
#define FUNKCJA_ZABEZPIECZENIA_CWU 1151
#define SONDA_ZASILANIE 1152
#define TEMP_KONTROLNA 1153
#define TEMP_DODATKOWE_ZRODLO 1154
#define ZADANA_ZBIORNIKA 1155
#define ANTYZAMARZANIE_PROG 1156
#define ANTYZAMARZANIE_ZRODLO_CIEPLA 1157
#define PRACA_SPREZARKA 1158
#define PRZYPOMNIENIE_ANTYLEGIONELLA 1159
#define MINMAX_ZADANA_ZBIORNIKA 1160
#define MINMAX_ANTYZAMARZANIE 1161
#define TESTUJ_USB 1162
#define PRACA_GRZANIE 1163
#define PRACA_CHLODZENIE 1164
#define FUNKCJA_GWC 1165
#define GWC_CZAS_POZOSTALY 1166
#define PRACA_GWC 1167
#define TEMP_GWC_GORNA 1168
#define TEMP_GWC_DOLNA 1169
#define MINMAX_PODLOGOWA 1170
#define OCZYSZCZALNIA_ALARM_1 1171
#define OCZYSZCZALNIA_ALARM_2 1172
#define OCZYSZCZALNIA_ALARM_3 1173
#define OCZYSZCZALNIA_ALARM_4 1174
#define OCZYSZCZALNIA_ALARM_5 1175
#define ZADANA_BUFORA 1176

#define BIEG_PRZEDMUCHU 1177
#define CZAS_PODSYPU 1178
#define CZAS_OPOZNIENIA 1179
#define CZAS_PODAWANIA 1180
#define PRZERWA_PODAWANIA 1181
#define OBROTY_WENTYLATORA 1182
#define OBROTY_WENTYLATORA2 1183
#define ZABEZPIECZENIE_GRZALKI 1184
#define OPOZNIENIE_WENTYLATORA 1185
#define CZAS_PRZEDMUCHU 1186

#define MINIMALNA_PRACA 1187
#define MAKSYMALNA_PRACA 1188
#define MINIMALNA_PRZERWA 1189
#define MAKSYMALNA_PRZERWA 1190
#define MIN_WENT_ROBOCZY 1191
#define MAKS_WENT_ROBOCZY 1192

#define OKRES_CZYSZCZENIA 1193
#define KONTROLA_PRACY 1194

#define OBROTY_WENTYLATORA_WYGASZANIE 1195
#define CZAS_PODAWANIA_WYGASZANIE 1196
#define PRZERWA_PODAWANIA_WYGASZANIE 1197
#define CZAS_WYGASZANIA_WYGASZANIE 1198
#define CZAS_OPOZNIENIA_WYGASZANIE 1199
#define FLAGI_ROZPALANIA_WYGASZANIA_POKOJOWKA 1200 // flagi bitowe przesyłane do pokojówki. Definicje flag znajdują się w common.h i rozpoczynają się od FLAGA_POKOJOWKA_ROZPALANIE_ i FLAGA_POKOJOWKA_WYGASZANIE_

#define CZUJNIK_CISNIENIA_ROZNICA_CISNIEN 1201  //jednostka Pa/10
#define CZUJNIK_CISNIENIA_TEMPERATURA 1202

#define INWERSJA_STYKU_BEZNAPIECIOWEGO 1203
#define TYGODNIOWKA_ZMIANA_ZADANEJ_CWU 1204

#define GRZANIE_PODLOGOWE 1205
#define FUNKCJA_BUFORA 1206

#define ZADANA_BUFORA_GORA 1207
#define MIN_MAX_BUFORA_GORA 1208

#define ZADANA_BUFORA_DOL 1209
#define MIN_MAX_BUFORA_DOL 1210

#define BYPASS_ZAWSZE_OTWARTY 1211
#define BYPASS_TEMP_MAX 1212
#define BYPASS_TEMP_MIN 1213
#define ANTYZAMARAZNIE_WYMIENNIKA_TEMP_GRANICZNA 1214
#define ANTYZAMARAZNIE_WYMIENNIKA_TEMP_SPOWOLNIENIA_WENT 1215
#define ANTYZAMARAZNIE_WYMIENNIKA_TEMP_ZATRZMANIA_WENT 1216
#define ANTYZAMARAZNIE_WYMIENNIKA_TEMP_AKTYW_GRZALKI 1217
#define ANTYZAMARAZNIE_WYMIENNIKA_MIN_CZAS_PRACY_GRZALKI 1218
#define ANTYZAMARAZNIE_WYMIENNIKA_MIN_MOC_WENT_Z_GRZALKA 1219
#define DODATKOWY_KOCIOL_TRYB 1220
#define DODATKOWY_KOCIOL_SCHEMAT 1221
#define MAX_TEMP_SPALIN_CZUWANIE 1222
#define PROG_PRZEPUSTNICA_WENTYLATOR 1223
#define CZAS_DELTA_POMPA 1224
#define MOC_WENTYLATORA_WE_CYFROWE_1 1225
#define MOC_WENTYLATORA_NAWIEW_PROC 1226
#define MOC_WENTYLATORA_WYWIEW_PROC 1227
#define PROG_CO2 1228
#define PROG_WILGOTNOSCI 1229
#define FUNKCJA_CZUJNIKA_CO2 1230
#define FUNKCJA_CZUJNIKA_WILGOTNOSCI 1231
#define OCHRONA_CO2_AKTYWNA 1232
#define OCHRONA_WILGOTNOSC_AKTYWNA 1233
#define CO2_PPM 1234
#define WILGOTNOSC 1235
#define MOC_WENTYLATORA_WE_CYFROWE_2 1236
#define TYP_NAGRZEWNICY_WTORNEJ 1237
#define TYP_CHLODNICY 1238
#define TYP_CZUJNIKA_WIODACEGO 1239
#define MODBUS_BAUDRATE 1240
#define MODBUS_SLAVE_ADDRESS 1241
#define GWC_ZAWSZE_OTWARTY 1242
#define PRACA_NAGRZEWNICA_PIERWOTNA 1243
#define ALGORYTM_PRACY_KOTLA 1244
#define TRYB_PRACY_KASKADA 1245
#define PRACA_KOTLA_KASKADA 1246
#define ILOSC_PIECY_KASKADA 1247
#define HISTEREZA_KASKADA 1248
#define DOLNA_GRANICA_WYDAJNOSCI_KASKADA 1249
#define DOGRZEWANIE 1250
#define OBROTY_DOGRZEWANIA 1251
#define CZAS_DOGRZEWANIA 1252
#define TEMP_ZAL_JEDNEGO_PIECA_KASKADA 1253
#define TEMP_ZAL_DWOCH_PIECY_KASKADA 1254
#define TEMP_ZAL_TRZECH_PIECY_KASKADA 1255
#define TEMP_ZAL_CZTERECH_PIECY_KASKADA 1256
#define ZALACZ_P1_CZAS 1257
#define ZALACZ_P2_CZAS 1258
#define TEMP_GRANICZNA_WYMIENNIKA_HI 1259
#define TEMP_GRANICZNA_WYMIENNIKA_LO 1260
#define HISTEREZA_BYPASSU 1261
#define CZAS_OCZEKIWANIA_KASKADA 1262
#define ETHERNET_START_REJESTRACJA 1263
#define ETHERNET_KOD_REJESTRACJI 1264
#define ROBOCZE_MAX_WENTYLATORA_NAWIEWU 1265 //rekuperator
#define ROBOCZE_MAX_WENTYLATORA_WYWIEWU 1266 //rekuperator
#define ROBOCZE_MIN_WENTYLATORA_NAWIEWU 1267 //rekuperator
#define ROBOCZE_MIN_WENTYLATORA_WYWIEWU 1268 //rekuperator
#define POJEMNOSC_BUFORA 1269
#define KOREKTA_BIEGU_NAWIEWU_GWC 1270
#define CZAS_DRZEMKI 1271					//	czas trwania drzemki/standby
#define RODZAJ_POMIARU_KASKADA 1272
#define KOCIOL_WIODACY_KASKADA 1273
#define RODZAJ_CZUJNIKA_KASKADA 1274
#define TEMP_Z_CZUJNIKA_KASKADA 1275
#define POZIOM_BATERII 1276
#define KRYTYCZNY_POZIOM_PALIWA 1277
#define OTWARCIE_ZAWORU_GRZANIA_RECZNA 1278
#define OTWARCIE_ZAWORU_CHLDOZENIA_RECZNA 1279
#define CZESTOTLIWOSC_PWM 1280
#define MINIMALNE_OTWARCIE_ZAWORU 1281

#define MBUS_ADRES_URZADZENIA 1282
#define MBUS_KOMUNIKACJA_Z_URZADZENIEM 1283
#define MBUS_NR_FABRYCZNY 1284
#define MBUS_DATA_A 1285
#define MBUS_DATA_B 1286
#define MBUS_KODY_BLEDOW 1287
#define MBUS_CIEPLO_A 1288
#define MBUS_CIEPLO_B 1289
#define MBUS_CIEPLO_C 1290
#define MBUS_CIEPLO_D 1291
#define MBUS_OBJETOSC_GLOWNA 1292
#define MBUS_PRZEPLYW_CHWILOWY 1293
#define MBUS_MOC_CHWILOWA 1294
#define MBUS_TEMPERATURA_ZASILANIA 1295
#define MBUS_TEMPERATURA_POWROTU 1296
#define MBUS_CZAS_PRACY_A 1297
#define MBUS_CZAS_PRACY_B 1298
#define MBUS_CZAS_PRACY_Z_BLEDEM_A 1299
#define MBUS_CZAS_PRACY_Z_BLEDEM_B 1230
#define MBUS_TEST_METROLOGICZNY 1231
#define MBUS_WERSJA 1302
#define INFORMACJA 1303
#define INFORMACJA_KASUJ 1304

#define AKTUALNY_POZIOM_CO CO2_PPM//get Aktualne stężenie CO
#define	TEMPERATURA_CZUJNIKA TEMP_POKOJOWA //Temperatura czujnika CO
#define CZAS_DO_ALARMU 1305 //get Czas do zgłoszenia alarmu
#define PROG_CO_I 1306 //get wartość dla progu I
#define PROG_CO_CZAS_I 1307 //get czas po którym nastąpi alarm dla progu I
#define PROG_CO_II 1308 //get wartość dla progu II
#define PROG_CO_CZAS_II 1309 //get czas po którym nastąpi alarm dla progu II
#define PROG_CO_III 1310 //get wartość dla progu III
#define PROG_CO_CZAS_III 1311//get czas po którym nastąpi alarm dla progu III
#define PROG_CO_IV 1312//get wartość dla progu IV
#define NUMER_PROGU 1313//get Numer progu zagrożenia
#define SLABA_BATERIA 1314//get Slaba bateria
#define PROCENT_BATERJI 1315//get Procent naładowania baterii
#define TEST_STEROWNIKA 1316//get uruchomiono procedurę testująca
#define CZULOSC_CO 1317//Set ustawiajacy czujlosc czujnika CO w pA/ppm
#define JEST_ALARM_CO 1318//get zwracajcy czy wystapil alarm CO

#define BLOKADA_STEROWNIKA_STATUS 1319
#define TEMPERATURA_KOMFORTU 1320		// temperatura pomieszczenia po ktorej bypass sie zamyka
#define WYDAJNOSC_PRACY_BYPASS 1321
#define SWIETO_STATUS 1322
#define KOD_STATUS 1323
#define FUNKCJA_BYPASS 1324
#define GWC_WIETRZENIE_STATUS 1325
#define WARIANT_STYKU 1326
#define CZUJNIK_DODATKOWY_WARIANT 1327
#define TEMP_CZUJNIK_DODATKOWY 1328
#define CZUJNIK_DODATKOWY 1329

#define ADDRESS_1 1330
#define ADDRESS_2 1331

#define WERSJA_TESTOWA 1332

#define MIERNIK_MOCY_NAPIECIE 1333
#define MIERNIK_MOCY_HZ 1334
#define MIERNIK_MOCY_ACTIV_POWER 1335
#define MIERNIK_MOCY_POWER_FACTOR 1336
#define MIERNIK_MOCY_ANALOG_INPUT 1337
#define MIERNIK_MOCY_CURRENT_RMS 1338
#define MIERNIK_MOCY_REACTIV_POWER 1339
#define MIERNIK_MOCY_APPARENT_POWER 1440
#define MIERNIK_MOCY_WERSJA 1441

#define GET(x) (x)
#define SET(x) (x + 5000)

#endif


