#ifndef WTP_ADDRESS_CONSTS_H_
#define WTP_ADDRESS_CONSTS_H_

#define WTP_ADDRESS_UNINITIALIZED     0x0U
#define WTP_ADDRESS_BROADCAST         0xFFFFFFFFU

#define WTP_ADDRESS_FORBIDDEN_1       WTP_ADDRESS_UNINITIALIZED
#define WTP_ADDRESS_FORBIDDEN_2       WTP_ADDRESS_BROADCAST

#endif /* WTP_ADDRESS_CONSTS_H_ */
